/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as PositionsRouteImport } from './routes/positions'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSyncTradesRouteImport } from './routes/api/sync-trades'
import { Route as ApiSyncScannerRouteImport } from './routes/api/sync-scanner'
import { Route as ApiSyncBalanceRouteImport } from './routes/api/sync-balance'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsRoute = PositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncTradesRoute = ApiSyncTradesRouteImport.update({
  id: '/api/sync-trades',
  path: '/api/sync-trades',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncScannerRoute = ApiSyncScannerRouteImport.update({
  id: '/api/sync-scanner',
  path: '/api/sync-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncBalanceRoute = ApiSyncBalanceRouteImport.update({
  id: '/api/sync-balance',
  path: '/api/sync-balance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/patterns': typeof PatternsRoute
  '/positions': typeof PositionsRoute
  '/radar': typeof RadarRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/trades': typeof TradesRoute
  '/watchlist': typeof WatchlistRoute
  '/api/sync-balance': typeof ApiSyncBalanceRoute
  '/api/sync-scanner': typeof ApiSyncScannerRoute
  '/api/sync-trades': typeof ApiSyncTradesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/patterns': typeof PatternsRoute
  '/positions': typeof PositionsRoute
  '/radar': typeof RadarRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/trades': typeof TradesRoute
  '/watchlist': typeof WatchlistRoute
  '/api/sync-balance': typeof ApiSyncBalanceRoute
  '/api/sync-scanner': typeof ApiSyncScannerRoute
  '/api/sync-trades': typeof ApiSyncTradesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/patterns': typeof PatternsRoute
  '/positions': typeof PositionsRoute
  '/radar': typeof RadarRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/trades': typeof TradesRoute
  '/watchlist': typeof WatchlistRoute
  '/api/sync-balance': typeof ApiSyncBalanceRoute
  '/api/sync-scanner': typeof ApiSyncScannerRoute
  '/api/sync-trades': typeof ApiSyncTradesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/login'
    | '/manual'
    | '/patterns'
    | '/positions'
    | '/radar'
    | '/reports'
    | '/settings'
    | '/statistics'
    | '/trades'
    | '/watchlist'
    | '/api/sync-balance'
    | '/api/sync-scanner'
    | '/api/sync-trades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/login'
    | '/manual'
    | '/patterns'
    | '/positions'
    | '/radar'
    | '/reports'
    | '/settings'
    | '/statistics'
    | '/trades'
    | '/watchlist'
    | '/api/sync-balance'
    | '/api/sync-scanner'
    | '/api/sync-trades'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/login'
    | '/manual'
    | '/patterns'
    | '/positions'
    | '/radar'
    | '/reports'
    | '/settings'
    | '/statistics'
    | '/trades'
    | '/watchlist'
    | '/api/sync-balance'
    | '/api/sync-scanner'
    | '/api/sync-trades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  LoginRoute: typeof LoginRoute
  ManualRoute: typeof ManualRoute
  PatternsRoute: typeof PatternsRoute
  PositionsRoute: typeof PositionsRoute
  RadarRoute: typeof RadarRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StatisticsRoute: typeof StatisticsRoute
  TradesRoute: typeof TradesRoute
  WatchlistRoute: typeof WatchlistRoute
  ApiSyncBalanceRoute: typeof ApiSyncBalanceRoute
  ApiSyncScannerRoute: typeof ApiSyncScannerRoute
  ApiSyncTradesRoute: typeof ApiSyncTradesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions': {
      id: '/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof PositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync-trades': {
      id: '/api/sync-trades'
      path: '/api/sync-trades'
      fullPath: '/api/sync-trades'
      preLoaderRoute: typeof ApiSyncTradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync-scanner': {
      id: '/api/sync-scanner'
      path: '/api/sync-scanner'
      fullPath: '/api/sync-scanner'
      preLoaderRoute: typeof ApiSyncScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync-balance': {
      id: '/api/sync-balance'
      path: '/api/sync-balance'
      fullPath: '/api/sync-balance'
      preLoaderRoute: typeof ApiSyncBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  LoginRoute: LoginRoute,
  ManualRoute: ManualRoute,
  PatternsRoute: PatternsRoute,
  PositionsRoute: PositionsRoute,
  RadarRoute: RadarRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StatisticsRoute: StatisticsRoute,
  TradesRoute: TradesRoute,
  WatchlistRoute: WatchlistRoute,
  ApiSyncBalanceRoute: ApiSyncBalanceRoute,
  ApiSyncScannerRoute: ApiSyncScannerRoute,
  ApiSyncTradesRoute: ApiSyncTradesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
